const projects = [
	{
		id: 0,
		title: "Guap",
		logo: "guap_logo.png",
		images: [
			{ src: "guapcover.png", alt: "Cover for guap" },
			{ src: "guap1.png", alt: "Guap screenshot" },
			{ src: "guap2.png", alt: "Guap screenshot" },
			{ src: "guap3.png", alt: "Guap screenshot" },
			{ src: "guap4.png", alt: "Guap screenshot" },
			{ src: "guap5.png", alt: "Guap screenshot" },
			{ src: "guap6.png", alt: "Guap screenshot" },
			{ src: "guap7.png", alt: "Guap screenshot" },
			{ src: "guap8.png", alt: "Guap screenshot" },
			{ src: "guap9.png", alt: "Guap screenshot" },
			{ src: "guap10.png", alt: "Guap screenshot" },
		],
		technology: ["Next.js", "framer_motion", "django"],
		reviewer: {
			name: "Munyaradzi Chiwundura",
			profile: "munya.png",
			link: "therealmunya.vercel.app",
		},
		review: "Leave it to me to review my own work, well done Munya",
		rating: ["⭐", "⭐", "⭐", "⭐", "⭐"],
		sourceCode: "https://github.com/munyachiwundura/guap",
		link: "https://guap.vercel.app",
	},
	{
		id: 1,
		title: "Juicy Kotas",
		logo: "guap_logo.png",

		images: [
			{ src: "juicykotascover.png", alt: "Cover for Juicy Kota's" },
			{ src: "guap1.png", alt: "Guap screenshot" },
			{ src: "guap2.png", alt: "Guap screenshot" },
			{ src: "guap3.png", alt: "Guap screenshot" },
			{ src: "guap4.png", alt: "Guap screenshot" },
			{ src: "guap5.png", alt: "Guap screenshot" },
			{ src: "guap6.png", alt: "Guap screenshot" },
			{ src: "guap7.png", alt: "Guap screenshot" },
			{ src: "guap8.png", alt: "Guap screenshot" },
			{ src: "guap9.png", alt: "Guap screenshot" },
			{ src: "guap10.png", alt: "Guap screenshot" },
		],
		technology: ["Next.js", "framer_motion", "django"],
		description: "A passion project of mine",
		reviewer: {
			name: "Munyaradzi Chiwundura",
			profile: "munya.png",
			link: "therealmunya.vercel.app",
		},
		review: "Leave it to me to review my own work, well done Munya",
		rating: ["⭐", "⭐", "⭐", "⭐", "⭐"],
		sourceCode: "https://github.com/munyachiwundura/todo-app-v2",
		link: "https://thebreadbasket.vercel.app",
	},
	{
		id: 2,
		title: "Lorra's Closet",
		logo: "guap_logo.png",

		images: [
			{ src: "lorrasclosetcover.png", alt: "Cover for Lorra's Closet" },
			{ src: "guap1.png", alt: "Guap screenshot" },
			{ src: "guap2.png", alt: "Guap screenshot" },
			{ src: "guap3.png", alt: "Guap screenshot" },
			{ src: "guap4.png", alt: "Guap screenshot" },
			{ src: "guap5.png", alt: "Guap screenshot" },
			{ src: "guap6.png", alt: "Guap screenshot" },
			{ src: "guap7.png", alt: "Guap screenshot" },
			{ src: "guap8.png", alt: "Guap screenshot" },
			{ src: "guap9.png", alt: "Guap screenshot" },
			{ src: "guap10.png", alt: "Guap screenshot" },
		],
		technology: ["Next.js", "framer_motion", "django"],
		description: "A passion project of mine",
		reviewer: {
			name: "Munyaradzi Chiwundura",
			profile: "munya.png",
			link: "therealmunya.vercel.app",
		},
		review: "Leave it to me to review my own work, well done Munya",
		rating: ["⭐", "⭐", "⭐", "⭐", "⭐"],
		sourceCode: "https://github.com/munyachiwundura/todo-app-v2",
		link: "https://thebreadbasket.vercel.app",
	},
	{
		id: 3,
		title: "My Portfolio V1",
		logo: "guap_logo.png",

		images: [
			{ src: "myportfoliocover.png", alt: "Cover for my first portfolio" },
			{ src: "guap1.png", alt: "Guap screenshot" },
			{ src: "guap2.png", alt: "Guap screenshot" },
			{ src: "guap3.png", alt: "Guap screenshot" },
			{ src: "guap4.png", alt: "Guap screenshot" },
			{ src: "guap5.png", alt: "Guap screenshot" },
			{ src: "guap6.png", alt: "Guap screenshot" },
			{ src: "guap7.png", alt: "Guap screenshot" },
			{ src: "guap8.png", alt: "Guap screenshot" },
			{ src: "guap9.png", alt: "Guap screenshot" },
			{ src: "guap10.png", alt: "Guap screenshot" },
		],
		technology: ["Next.js", "framer_motion", "django"],
		description: "A passion project of mine",
		reviewer: {
			name: "Munyaradzi Chiwundura",
			profile: "munya.png",
			link: "therealmunya.vercel.app",
		},
		review: "Leave it to me to review my own work, well done Munya",
		rating: ["⭐", "⭐", "⭐", "⭐", "⭐"],
		sourceCode: "https://github.com/munyachiwundura/todo-app-v2",
		link: "https://thebreadbasket.vercel.app",
	},
	{
		id: 4,
		title: "Overkill To-do App",
		logo: "guap_logo.png",

		images: [
			{ src: "Todoappcover.png", alt: "Cover for Overkill to-do app" },
			{ src: "guap1.png", alt: "Guap screenshot" },
			{ src: "guap2.png", alt: "Guap screenshot" },
			{ src: "guap3.png", alt: "Guap screenshot" },
			{ src: "guap4.png", alt: "Guap screenshot" },
			{ src: "guap5.png", alt: "Guap screenshot" },
			{ src: "guap6.png", alt: "Guap screenshot" },
			{ src: "guap7.png", alt: "Guap screenshot" },
			{ src: "guap8.png", alt: "Guap screenshot" },
			{ src: "guap9.png", alt: "Guap screenshot" },
			{ src: "guap10.png", alt: "Guap screenshot" },
		],
		technology: ["Next.js", "framer_motion", "django"],
		description: "A passion project of mine",
		reviewer: {
			name: "Munyaradzi Chiwundura",
			profile: "munya.png",
			link: "therealmunya.vercel.app",
		},
		review: "Leave it to me to review my own work, well done Munya",
		rating: ["⭐", "⭐", "⭐", "⭐", "⭐"],
		sourceCode: "https://github.com/munyachiwundura/todo-app-v2",
		link: "https://thebreadbasket.vercel.app",
	},
	{
		id: 5,
		title: "The Bread Basket",
		logo: "guap_logo.png",

		images: [
			{ src: "thebreadbasketcover.png", alt: "Cover for The Bread Basket" },
			{ src: "guap1.png", alt: "Guap screenshot" },
			{ src: "guap2.png", alt: "Guap screenshot" },
			{ src: "guap3.png", alt: "Guap screenshot" },
			{ src: "guap4.png", alt: "Guap screenshot" },
			{ src: "guap5.png", alt: "Guap screenshot" },
			{ src: "guap6.png", alt: "Guap screenshot" },
			{ src: "guap7.png", alt: "Guap screenshot" },
			{ src: "guap8.png", alt: "Guap screenshot" },
			{ src: "guap9.png", alt: "Guap screenshot" },
			{ src: "guap10.png", alt: "Guap screenshot" },
		],
		technology: ["Django", "Next.js", "framer_motion"],
		description: "A passion project of mine",
		reviewer: {
			name: "Munyaradzi Chiwundura",
			profile: "munya.png",
			link: "therealmunya.vercel.app",
		},
		review: "Leave it to me to review my own work, well done Munya",
		rating: ["⭐", "⭐", "⭐", "⭐", "⭐"],
		sourceCode: "https://github.com/munyachiwundura/todo-app-v2",
		link: "https://thebreadbasket.vercel.app",
	},
];

export { projects };
